/* This file is autogenerated using the script in codegen/build_decode.py */

#include "c8Decode.h"
c8Func decode(uint16_t opcode)
{
  if(match_opcode(opcode,0x00E0,0xFFFF))
       return c8_CLS;
  if(match_opcode(opcode,0x00EE,0xFFFF))
       return c8_RET;
// Our emu ignores SYS
//  if(match_opcode(opcode,0x0000,0xF000))
//       return c8_SYS;
  if(match_opcode(opcode,0x1000,0xF000))
       return c8_JP;
  if(match_opcode(opcode,0x2000,0xF000))
       return c8_CALL;
  if(match_opcode(opcode,0x3000,0xF000))
       return c8_SE;
  if(match_opcode(opcode,0x4000,0xF000))
       return c8_SNE;
  if(match_opcode(opcode,0x5000,0xF00F))
       return c8_SE;
  if(match_opcode(opcode,0x6000,0xF000))
       return c8_LD;
  if(match_opcode(opcode,0x7000,0xF000))
       return c8_ADD;
  if(match_opcode(opcode,0x8000,0xF00F))
       return c8_LD;
  if(match_opcode(opcode,0x8001,0xF00F))
       return c8_OR;
  if(match_opcode(opcode,0x8002,0xF00F))
       return c8_AND;
  if(match_opcode(opcode,0x8003,0xF00F))
       return c8_XOR;
  if(match_opcode(opcode,0x8004,0xF00F))
       return c8_ADD;
  if(match_opcode(opcode,0x8005,0xF00F))
       return c8_SUB;
  if(match_opcode(opcode,0x8006,0xF00F))
       return c8_SHR;
  if(match_opcode(opcode,0x8007,0xF00F))
       return c8_SUBN;
  if(match_opcode(opcode,0x800E,0xF00F))
       return c8_SHL;
  if(match_opcode(opcode,0x9000,0xF00F))
       return c8_SNE;
  if(match_opcode(opcode,0xA000,0xF000))
       return c8_LD;
  if(match_opcode(opcode,0xB000,0xF000))
       return c8_JP;
  if(match_opcode(opcode,0xC000,0xF000))
       return c8_RND;
  if(match_opcode(opcode,0xD000,0xF000))
       return c8_DRW;
  if(match_opcode(opcode,0xE09E,0xF0FF))
       return c8_SKP;
  if(match_opcode(opcode,0xE0A1,0xF0FF))
       return c8_SKNP;
  if(match_opcode(opcode,0xF007,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF00A,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF015,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF018,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF01E,0xF0FF))
       return c8_ADD;
  if(match_opcode(opcode,0xF029,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF033,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF055,0xF0FF))
       return c8_LD;
  if(match_opcode(opcode,0xF065,0xF0FF))
       return c8_LD;
}
